### ISSUE TITLE
Integration with Bitrise

### ISSUE THREAD

**Issue by AntonioFerreira94** [FutureWorkshops/bitrise-step-create-apple-documentation#1]
Hello there!

I'm currently trying to integrate Jazzy on Bitrise, I found you're step, and I'm guessing it does the job of running Jazzy to deliver the Docs.

So I've implemented it after pulling the code from the repository. But when it comes the time to run your step, it returns the following error:
 create-apple-documentation@1.0.0 (exit code: 1)

Here's the configuration:
Configs:
  * project_path: ./
  * language: swift
  * author: Unknown
  * sdk: iphone
  * version: 1.0.0
  * framework_root: ./
  * module: First_Test
  * acl: public
  * output: ./docs
  * readme: ../README.md
  * title: Unknown Documentation
  * copyright: 
  * umbrella_header:

Am I doing something wrong? One note is that my project has a white space on its name, so its like: "First Test".

Can you give me some help?

Thanks!
António Ferreira.

**Comment by igorcferreira** [comment]
Hello @AntonioFerreira94. Could you provide the full log of the step (if possible)? Also: Which Bitrise stack are you using?

**Comment by AntonioFerreira94** [comment]
I'm using the latest stack (Xcode 11.4.x, mac OS 10.15.3 Catalina).
Here it is, thank you for the quick response! 
[775be219c96b871b.log](https://github.com/FutureWorkshops/bitrise-step-create-apple-documentation/files/4402314/775be219c96b871b.log)

**Comment by igorcferreira** [comment]
> I'm using the latest stack (Xcode 11.4.x, mac OS 10.15.3 Catalina).
> Here it is, thank you for the quick response!
> [775be219c96b871b.log](https://github.com/FutureWorkshops/bitrise-step-create-apple-documentation/files/4402314/775be219c96b871b.log)

@AntonioFerreira94 Thanks for the information, and bug report. Looking at the information provided, I believe I found where the issue lives.

Looking at the logs, I see:

```
Configs:
  * project_path: ./
  * language: swift
  * author: <Author Name>
  * sdk: iphone
  * version: 1.0.0
  * framework_root: .
  * module: <Project Name> (Development)
  * acl: public
  * output: ./docs
  * readme: ./README.md
  * title: <Project Name> Swift
  * copyright: 
  * umbrella_header: 
```

I see the module name as: `<Project Name>  (Development)`.

Looking at the script, the space in the module name will break the code, and it is something that needs to be fixed. Sorry for the problem.

This module input is used as:

- For Swift projects, jazzy needs to build the project. So, the script expects the module to be the same name of the scheme that will be used to build the project:

```
xcodebuild --clean --build-tool-arguments -scheme,$(echo $module)
```

But, I would like to ask you if your shared scheme (or default project scheme) contains the space? If not, changing the `module` input to match your scheme naming may allow you to unblock your build, until we manage to publish a fixed version of the step.

**Comment by AntonioFerreira94** [comment]
Thanks! No problem! :)
How do I check the scheme name?

**Comment by igorcferreira** [comment]
> Thanks! No problem! :)
> How do I check the scheme name?

You can find it on Xcode. In the action panel. The scheme should be the one used to run the target.

<img width="537" alt="Screenshot 2020-03-30 at 13 48 48" src="https://user-images.githubusercontent.com/2117340/77909255-575eb080-728d-11ea-9772-0b2fabb29fbb.png">

**Comment by AntonioFerreira94** [comment]
> > Thanks! No problem! :)
> > How do I check the scheme name?
> 
> You can find it on Xcode. In the action panel. The scheme should be the one used to run the target.
> 
> <img alt="Screenshot 2020-03-30 at 13 48 48" width="537" src="https://user-images.githubusercontent.com/2117340/77909255-575eb080-728d-11ea-9772-0b2fabb29fbb.png">

Yes its, TEST TEST (Development)

**Comment by AntonioFerreira94** [comment]
> > Thanks! No problem! :)
> > How do I check the scheme name?
> 
> You can find it on Xcode. In the action panel. The scheme should be the one used to run the target.
> 
> <img alt="Screenshot 2020-03-30 at 13 48 48" width="537" src="https://user-images.githubusercontent.com/2117340/77909255-575eb080-728d-11ea-9772-0b2fabb29fbb.png">

Also please could you hide the references for the project name on the previous comments? :)

**Comment by igorcferreira** [comment]
@AntonioFerreira94 I'm sorry. I removed the explicit name for the comments.

**Comment by AntonioFerreira94** [comment]
> @AntonioFerreira94 I'm sorry. I removed the explicit name for the comments.

No problem! Thanks for the help. Let me know when the fix goes live! :)

**Comment by igorcferreira** [comment]
@AntonioFerreira94 I opened a [PR on Bitrise's step lib](https://github.com/bitrise-io/bitrise-steplib/pull/2442) with the update to 1.1.0, and the fix to the reported issue.
